# Generated by Django 3.1.4 on 2021-01-01 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='TodoItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateField(default='2021-01-01')),
                ('due_date', models.DateField(default='2021-01-01')),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.SET_DEFAULT, to='todo.category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
